### ISSUE TITLE
Fix riot-android translation instructions

### ISSUE THREAD

**Issue by Matrixcoffee** [Matrixcoffee/matrix-knowledge-base#36] opened 2017-06-14 23:09 UTC

**Comment by Matrixcoffee** [comment] 2017-06-15 19:01
https://translate.riot.im

**Comment by nvbln** [comment] 2017-10-13 18:41
Isn't this a duplicate of #35?

And isn't this issue already fixed by PR #45?

**Comment by Matrixcoffee** [comment] 2017-10-13 18:46
Indeed. Thanks.

**Closed** 2017-10-13 18:46 UTC
